#/bin/bash
docker container stop ocean-aquarius-1
docker container stop ocean-graph-node-1
docker container stop ocean-subgraph-1
docker container stop ocean-ipfs-1
docker container stop ocean-postgres-1
docker container stop ocean-provider-1
docker container stop ocean-provider2-1
docker container stop ocean-ocean-contracts-1
docker container stop ocean-elasticsearch-1
docker container stop ocean-typesense-1
docker container stop ocean-ganache-1
docker container stop ocean-faucet-1
docker container stop ocean-computetodata-1
docker container stop ocean-kindcluster-1
docker container stop ocean-redis-1
docker container stop ocean-dashboard-1
docker container stop docker-registry
docker container stop ocean-pdr-trader-1
docker container stop ocean-pdr-predictoor1-1
docker container stop ocean-pdr-predictoor2-1
docker container stop ocean-pdr-predictoor3-1
docker container stop ocean-pdr-trueval-1
docker container stop ocean-pdr-publisher-1
docker container stop ocean-pdr-dfbuyer-1
docker container rm ocean-aquarius-1
docker container rm ocean-graph-node-1
docker container rm ocean-subgraph-1
docker container rm ocean-ipfs-1
docker container rm ocean-postgres-1
docker container rm ocean-provider-1
docker container rm ocean-provider2-1
docker container rm ocean-ocean-contracts-1
docker container rm ocean-elasticsearch-1
docker container rm ocean-typesense-1
docker container rm ocean-ganache-1
docker container rm ocean-faucet-1
docker container rm ocean-computetodata-1
docker container rm ocean-kindcluster-1
docker container rm ocean-redis-1
docker container rm ocean-dashboard-1
docker container rm docker-registry
docker container rm ocean-pdr-trader-1
docker container rm ocean-pdr-predictoor1-1
docker container rm ocean-pdr-predictoor2-1
docker container rm ocean-pdr-predictoor3-1
docker container rm ocean-pdr-trueval-1
docker container rm ocean-pdr-publisher-1
docker container rm ocean-pdr-dfbuyer-1
docker volume rm ocean-graphipfs
docker volume rm ocean-graphpgsql
docker volume rm ocean-provider1db
docker volume rm ocean-provider2db

docker network rm kind
docker volume rm $(docker volume ls -q)
