version: '2.1'

services:
  mongodb:
    image: mongo:3.6
    command: mongod
    networks:
    - backend

  keeper-contracts:
    image: oceanprotocol/keeper-contracts:${OCEAN_VERSION:-stable}
    ports:
    - 8545:8545
    networks:
    - backend
    environment:
      LOCAL_CONTRACTS: "true"
      DEPLOY_CONTRACTS: ${DEPLOY_CONTRACTS}
      DATABASE_PATH: "/ganache-db"
      REUSE_DATABASE: ${REUSE_DATABASE}
      NETWORK_NAME: ${KEEPER_NETWORK_NAME}
    volumes:
    - ${ARTIFACTS_FOLDER}:/keeper-contracts/artifacts/
    - ${GANACHE_DATABASE_PATH}/ganache-db:/ganache-db

  aquarius:
    image: oceanprotocol/aquarius:${OCEAN_VERSION:-stable}
    ports:
    - 5000:5000
    networks:
    - backend
    depends_on:
    - keeper-contracts
    environment:
      KEEPER_URL: http://keeper-contracts:8545
      DB_HOSTNAME: mongodb
      LOCAL_CONTRACTS: "true"
    volumes:
    - ${ARTIFACTS_FOLDER}:/usr/local/keeper-contracts/:ro

  brizo:
    image: oceanprotocol/brizo:${OCEAN_VERSION:-stable}
    ports:
    - 8030:8030
    networks:
    - backend
    depends_on:
    - keeper-contracts
    env_file:
      - ${BRIZO_ENV_FILE}
    environment:
      KEEPER_URL: http://keeper-contracts:8545
    volumes:
    - ${ARTIFACTS_FOLDER}:/usr/local/keeper-contracts/:ro

networks:
  backend:


