version: '2.1'
services:
  parity-node:
    image: oceanprotocol/parity-ethereum:master
    # entrypoint: tail
    # command: ["-f", "/dev/null"]
    # network_mode: host
    entrypoint: /opt/parity/parity
    command:
      --config /etc/parity/$NETWORK/config.toml
      --base-path /parity_data
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --unsafe-expose
      --unlock $UNLOCK_ADDRESS
    volumes:
      - ./parity/$NETWORK/config.toml:/etc/parity/$NETWORK/config.toml
      - ./parity/$NETWORK/chain.json:/etc/parity/$NETWORK/chain.json
      - parity-$NETWORK-node:/parity_data/
      - ./parity/$NETWORK/account.json:/parity_data/keys/$NETWORK/account.json
      - ./parity/$NETWORK/password:/etc/parity/$NETWORK/password

volumes:
  parity-kovan-node:
  parity-ocean-network-node:
