[parity]
chain = "kovan"
base_path = "/parity_data"

[ui]
disable = true

[rpc]
disable = false

[ipc]
disable = true

[dapps]
disable = true

[websockets]
disable = true
port = 8546
interface = "local"
origins = ["none"]
apis = ["all"]
hosts = ["all"]

[network]
port = 30303

[ipfs]
enable = false

[snapshots]
disable_periodic = true

[secretstore]
disable = true

[account]
password = ["/etc/parity/kovan/password"]
