version: '3'
services:
  keeper-node:
    image: ${PARITY_IMAGE}
    command:
      --chain kovan
      --base-path /home/parity/base
      --keys-path /home/parity/.local/share/io.parity.ethereum/keys
      --light
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --unsafe-expose
    volumes:
      - ../networks/kovan/keys:/home/parity/.local/share/io.parity.ethereum/keys/kovan
      - keeper-node-kovan:/home/parity/.local/share/io.parity.ethereum/
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.12
