version: '2.1'
services:
  keeper-node:
    image: parity/parity${PARITY_VERSION}
    command:
      --chain kovan
      --base-path /home/parity/base
      --keys-path /home/parity/.local/share/io.parity.ethereum/keys
      --light
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --unsafe-expose
      --node-key 0xb3244c104fb56d28d3979f6cd14a8b5cf5b109171d293f4454c97c173a9f9374
    volumes:
      - ../networks/kovan/keys:/home/parity/.local/share/io.parity.ethereum/keys/kovan
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.12
