version: '2.1'
services:
  keeper-node:
    image: parity/parity${PARITY_VERSION}
    command:
      --config /home/parity/config/config.toml
      --db-path /home/parity/chains
      --keys-path /home/parity/.local/keys
      --base-path /home/parity/base
      --min-gas-price 0
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --unsafe-expose
      --unlock 0x00bd138abd70e2f00903268f3db08f2d25677c9e
    volumes:
      - ../networks/spree/config:/home/parity/config
      - ../networks/spree/authorities/validator0.json:/home/parity/.local/keys/spree/validator.json
      - ../networks/spree/keys:/home/parity/.local/keys/spree
      - ../networks/spree/authorities/validator0.pwd:/home/parity/validator.pwd:ro
      - ../networks/spree/node0.network.key:/home/parity/.local/share/io.parity.ethereum/network/key:ro
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.12
