version: '3'
services:
  agent:
    image: oceanprotocol/agent:$AGENT_VERSION
    networks:
      backend:
        ipv4_address: 172.15.0.26
    ports:
      - 4040:4040
    environment:
      LOCAL_CONTRACTS: ${KEEPER_DEPLOY_CONTRACTS}
      aquariusUri: ${AQUARIUS_URI}
      brizoAddress: ${PROVIDER_ADDRESS}
      nodeUri: ${KEEPER_RPC_URL}
      brizoUri: ${BRIZO_URL}
      secretstoreUri: ${SECRET_STORE_URL}
      faucetUri: ${FAUCET_URL}
      PRIVATE_KEY: ${AGENT_PRIVATE_KEY}
      enable_publish: 'true'
      enable_consume: 'true'
    volumes:
      - ${KEEPER_ARTIFACTS_FOLDER}:/usr/src/app/node_modules/@oceanprotocol/keeper-contracts/artifacts/:ro
      

