version: '2.1'
services:
  aquarius:
    image: oceanprotocol/aquarius:${OCEAN_VERSION:-stable}
    ports:
    - 5000:5000
    networks:
      backend:
        ipv4_address: 172.15.0.15
    depends_on:
    - mongodb
    environment:
      DB_HOSTNAME: mongodb
    volumes:
    - ${ARTIFACTS_FOLDER}:/usr/local/keeper-contracts/:ro
