version: '3'
services:
  aquarius:
    image: oceanprotocol/aquarius:${AQUARIUS_VERSION:-latest}
    ports:
      - 5000:5000
    networks:
      backend:
        ipv4_address: 172.15.0.5
    depends_on:
      - elasticsearch
      - ocean-contracts
    environment:
      SUBGRAPH_URLS: ${SUBGRAPH_URLS}
      DB_MODULE: ${DB_MODULE}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: ${DB_SSL}
      DB_VERIFY_CERTS: ${DB_VERIFY_CERTS}
      DB_CA_CERTS: ${DB_CA_CERTS}
      DB_CLIENT_KEY: ${DB_CLIENT_KEY}
      DB_CLIENT_CERT: ${DB_CLIENT_CERT}
      LOG_LEVEL: ${AQUARIUS_LOG_LEVEL}
      PRIVATE_KEY: "0x5d75837394b078ce97bc289fa8d75e21000573520bfa7784a9d28ccaae602bf8"
      ARTIFACTS_PATH: "/ocean-contracts/artifacts"
      ADDRESS_FILE: "/ocean-contracts/artifacts/address.json"
      DEPLOY_CONTRACTS: ${DEPLOY_CONTRACTS}
      NETWORK_NAME: ${CONTRACTS_NETWORK_NAME}
      EVENTS_RPC: "http://172.15.0.3:8545"
      EVENTS_ALLOW: "0"
      RUN_EVENTS_MONITOR: "1"
      AQUARIUS_URL: http://172.15.0.5:5000
      EVENTS_MONITOR_SLEEP_TIME: ${EVENTS_MONITOR_SLEEP_TIME}
      SUBGRAPH_URLS: |
              {"8996": "http://172.15.0.15:8000"}
    volumes:
    - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
