version: '3'
services:
  commonsserver:
    image: oceanprotocol/commons_server:$COMMONS_SERVER_VERSION
    networks:
      backend:
        ipv4_address: 172.15.0.23
    ports:
      - 4000:4000
    environment:
      IPFS_GATEWAY_URI: ${COMMONS_IPFS_GATEWAY_URI}

  commonsclient:
    image: oceanprotocol/commons_client:$COMMONS_CLIENT_VERSION
    networks:
      backend:
        ipv4_address: 172.15.0.24
    ports:
      - 3000:3000
    depends_on:
      - keeper-node
      - aquarius
      - brizo
      - commonsserver
    environment:
      LISTEN_ADDRESS: '0.0.0.0'
      LOCAL_CONTRACTS: ${KEEPER_DEPLOY_CONTRACTS}
      REACT_APP_ALLOW_PRICING: 'true'
      REACT_APP_SHOW_REQUEST_TOKENS_BUTTON: 'true'
      REACT_APP_AQUARIUS_URI: ${COMMONS_AQUARIUS_URI}
      REACT_APP_BRIZO_ADDRESS: ${PROVIDER_ADDRESS}
      REACT_APP_SERVICE_URI: ${COMMONS_SERVER_URL}
      REACT_APP_NODE_URI: ${COMMONS_KEEPER_RPC_HOST}
      REACT_APP_BRIZO_URI: ${COMMONS_BRIZO_URL}
      REACT_APP_SECRET_STORE_URI: ${COMMONS_SECRET_STORE_URL}
      REACT_APP_FAUCET_URI: ${COMMONS_FAUCET_URL}
      REACT_APP_IPFS_GATEWAY_URI: ${COMMONS_IPFS_GATEWAY_URI}
      REACT_APP_IPFS_NODE_URI: ${COMMONS_IPFS_NODE_URI}
    volumes:
      - ${KEEPER_ARTIFACTS_FOLDER}:/app/frontend/node_modules/@oceanprotocol/keeper-contracts/artifacts/:ro

