version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.5.1
    networks:
      backend:
        ipv4_address: 172.15.0.6
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      MAX_MAP_COUNT: "64000"
      discovery.type: "single-node"
