version: '2.1'
services:
  keeper-contracts:
    image: oceanprotocol/keeper-contracts:${OCEAN_VERSION:-stable}
    networks:
      backend:
        ipv4_address: 172.15.0.14
    environment:
      LOCAL_CONTRACTS: "true"
      DEPLOY_CONTRACTS: ${DEPLOY_CONTRACTS}
      DATABASE_PATH: "/ganache-db"
      REUSE_DATABASE: ${REUSE_DATABASE}
      NETWORK_NAME: ${KEEPER_NETWORK_NAME}
      POA_HOST: "parity-node"
    volumes:
    - ${ARTIFACTS_FOLDER}:/keeper-contracts/artifacts/
    - ${GANACHE_DATABASE_PATH}/ganache-db:/ganache-db
