version: '3'
services:
  node:
    image: ghcr.io/oceanprotocol/ocean-node:${NODE_VERSION:-latest}
    ports:
      - 8000:8000
      - 8001:8001
      - 9001:9001
    networks:
      ocean_backend:
        ipv4_address: 172.15.0.5
    depends_on:
      elasticsearch:
        condition: service_started
      ocean-contracts:
        condition: service_healthy
      ganache:
        condition: service_started
    environment:
      DB_TYPE: 'elasticsearch'
      DB_URL: ${DB_URL}
      DB_USERNAME: ${ELASTICSEARCH_USERNAME}
      DB_PASSWORD: ${ELASTIC_PASSWORD}
      PRIVATE_KEY: ${NODE_PRIVATE_KEY}
      IPFS_GATEWAY: ${IPFS_GATEWAY}
      ARWEAVE_GATEWAY: https://arweave.net/
      P2P_ipV4BindTcpPort: 8000
      HTTP_API_PORT: 8001
      RPCS: '{ "8996": {"rpc": "http://172.15.0.3:8545", "chainId": 8996, "network": "development", "chunkSize": 100} }'
      INDEXER_NETWORKS: '[8996]'
      INDEXER_INTERVAL: 1000
      LOG_LEVEL: DEBUG
      AUTHORIZED_DECRYPTERS: '["0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"]'
      P2P_ENABLE_UPNP: 'false'
      P2P_ENABLE_AUTONAT: 'false'
      ALLOWED_ADMINS: '["0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"]'
      MAX_REQ_PER_MINUTE: 320
      MAX_CONNECTIONS_PER_MINUTE: 320
      ADDRESS_FILE: "/ocean-contracts/artifacts/address.json"
      PERSISTENT_STORAGE: '{"enabled":true,"type":"localfs","options":{"folder":"/persistent-storage"}}'
      SERVICE_TEMPLATES_PATH: "docs/serviceTemplates/"
      DOCKER_COMPUTE_ENVIRONMENTS: "[{\"socketPath\":\"/var/run/docker.sock\",\"serviceOnDemand\":{\"enabled\":true,\"nodeHost\":\"localhost\",\"hostPortRange\":[30000,32000],\"maxDurationSeconds\":86400,\"allowImageBuild\":true},\"environments\":[{\"resources\":[{\"id\":\"cpu\",\"total\":4},{\"id\":\"ram\",\"total\":16},{\"id\":\"disk\",\"total\":50}],\"storageExpiry\":604800,\"maxJobDuration\":3600,\"features\":{\"computeJobs\":true,\"services\":true},\"fees\":{\"8996\":[{\"prices\":[{\"id\":\"cpu\",\"price\":1},{\"id\":\"ram\",\"price\":1}]}]},\"free\":{\"maxJobDuration\":60,\"maxJobs\":3,\"resources\":[{\"id\":\"cpu\",\"max\":1},{\"id\":\"ram\",\"max\":1},{\"id\":\"disk\",\"max\":1}]}}]}]"

    volumes:
    - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
    - /var/run/docker.sock:/var/run/docker.sock
    - ${NODE_PERSISTENT_STORAGE_FOLDER}:/persistent-storage
