version: '2.1'
services:
  parity-node:
    image: oceanprotocol/parity-ethereum:beta
    entrypoint: /opt/parity/parity
    command:
      --config /home/parity/parity/config/secretstoreclient.toml
      --db-path /home/parity/chains
      --keys-path /home/parity/.local/share/io.parity.ethereum/keys
      --base-path /home/parity/base
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --unsafe-expose
      --unlock 0x00bd138abd70e2f00903268f3db08f2d25677c9e
    volumes:
      - $DIR/parity/parity/config:/home/parity/parity/config
      - parity-node:/home/parity/.local/share/io.parity.ethereum/
      - $DIR/parity/parity/authorities/validator0.json:/home/parity/.local/share/io.parity.ethereum/keys/ocean-network/validator.json
      - $DIR/parity/parity/keys:/home/parity/.local/share/io.parity.ethereum/keys/ocean-network
      - $DIR/parity/parity/authorities/validator0.pwd:/home/parity/parity/validator.pwd
      - $DIR/parity/parity/node0.network.key:/home/parity/.local/share/io.parity.ethereum/network/key
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.12
