version: '3'
services:
  pleuston:
    image: oceanprotocol/pleuston:$PLEUSTON_VERSION
    networks:
      backend:
        ipv4_address: 172.15.0.19
    ports:
    - 3000:3000
    depends_on:
    - keeper-node
    - aquarius
    - brizo
    environment:
      # Need browser to connect to exposed ports
      KEEPER_HOST: localhost
      AQUARIUS_HOST: localhost
      LOCAL_CONTRACTS: ${KEEPER_DEPLOY_CONTRACTS}
    volumes:
    - ${KEEPER_ARTIFACTS_FOLDER}:/pleuston/node_modules/@oceanprotocol/keeper-contracts/artifacts/:ro
