version: '2.1'
services:
  secret-store:
    image: oceanprotocol/parity-ethereum${PARITY_ETHEREUM_VERSION}
    entrypoint: /entrypoint.sh
    environment:
      CONFIGURE_ACL: "${CONFIGURE_ACL}"
    command:
      --config /etc/parity/secretstore/config.toml
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --base-path /secret-store/
    volumes:
      - ../networks/secret-store/config/:/etc/parity/secretstore/
      - secret-store:/secret-store/
      - ../networks/secret-store/keys/:/secret-store/keys/secretstore/
      - ${KEEPER_ARTIFACTS_FOLDER}:/contracts
    ports:
      - 12000:12000
      - 12001
    networks:
      backend:
        ipv4_address: 172.15.0.13

  secret-store-cors-proxy:
    image: nginx${NGINX_VERSION}
    volumes:
      - ../cors-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - secret-store
    ports:
      - 12001:12001
    networks:
      backend:
        ipv4_address: 172.15.0.16
    command: nginx -g 'daemon off;'

  secret-store-signing-node:
    image: parity/parity${PARITY_VERSION}
    command:
      --chain dev
      --light
      --jsonrpc-interface all
      --jsonrpc-apis secretstore
      --jsonrpc-cors all
      --keys-path /home/parity/.local/keys
    ports:
      - 9545:8545
    volumes:
      - ../networks/secret-store/keys:/home/parity/.local/keys/DevelopmentChain:ro
    networks:
      backend:
        ipv4_address: 172.15.0.18
