version: '3'
services:
  secret-store:
    image: oceanprotocol/parity-ethereum:master
    entrypoint: /entrypoint.sh
    environment:
      CONFIGURE_ACL: "${CONFIGURE_ACL}"
      ACL_CONTRACT_ADDRESS: "${ACL_CONTRACT_ADDRESS}"
      NETWORK: "${KEEPER_NETWORK_NAME}"
    command:
      --chain /etc/parity/secretstore/chain_${KEEPER_NETWORK_NAME}.json
      --config /etc/parity/secretstore/config.toml
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --no-warp
      --node-key 0x32313aee5977ca63184b696e4cf7b7bfc2745f727dbef82d7a1f6314ad58dcf5
      --reserved-peers /etc/parity/secretstore/peers_${KEEPER_NETWORK_NAME}.txt
      -l secretstore_net,secretstore=trace
    volumes:
      - ../networks/secret-store/config/:/etc/parity/secretstore/
      - secret-store:/secret-store/
      - ../networks/secret-store/keys:/parity_data/keys
      - ${KEEPER_ARTIFACTS_FOLDER}:/contracts
    ports:
      - 12000:12000
      - 12001
    networks:
      backend:
        ipv4_address: 172.15.0.13

  secret-store-cors-proxy:
    image: nginx:alpine
    volumes:
      - ../cors-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - secret-store
    ports:
      - 12001:12001
    networks:
      backend:
        ipv4_address: 172.15.0.16
    command: nginx -g 'daemon off;'

  secret-store-signing-node:
    image: parity/parity:v2.3.2
    command:
      --chain /etc/parity/secretstore/chain_${KEEPER_NETWORK_NAME}.json
      --light
      --jsonrpc-interface all
      --jsonrpc-apis secretstore
      --jsonrpc-cors all
      --no-warp
      --keys-path /home/parity/.local/keys
      --node-key 0x27881af7f75724e25a9818f6c8e719895c8c9d3512003fc8ad0f47d762a07a79
      --reserved-peers /etc/parity/secretstore/peers_${KEEPER_NETWORK_NAME}.txt
    ports:
      - 9545:8545
    volumes:
      - ../networks/secret-store/keys:/home/parity/.local/keys
      - ../networks/secret-store/config/:/etc/parity/secretstore/
    networks:
      backend:
        ipv4_address: 172.15.0.18
