version: '2.1'
services:
  secret-store:
    image: oceanprotocol/parity-ethereum:master
    # entrypoint: tail -f /dev/null
    entrypoint: /opt/parity/parity
    command:
      --config /etc/parity/secretstore/config.toml --jsonrpc-cors all --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-apis all
    volumes:
    - ../parity/secret_store/config/:/etc/parity/secretstore/
    - secret-store:/parity_data/
    - ../parity/secret_store/keys/:/parity_data/keys/ocean-network/
    ports:
    - 12000:12000
    - 12001
    networks:
      backend:
        ipv4_address: 172.15.0.13

  secret-store-cors-proxy:
    image: nginx:alpine
    volumes:
      - ../cors-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - secret-store
    ports:
      - 12001:12001
    networks:
      backend:
        ipv4_address: 172.15.0.16
    command: nginx -g 'daemon off;'
