[supervisord]
nodaemon=true

[program:apache2]
command=/usr/sbin/apachectl -D FOREGROUND
autorestart=true

[program:vsftpd]
command=/usr/sbin/vsftpd /etc/vsftpd.conf
autorestart=true

[program:ceph-mon]
command=/usr/bin/ceph-mon -i a --foreground
autorestart=true

[program:ceph-mgr]
command=/usr/bin/ceph-mgr -i a
autorestart=true

[program:ceph-osd]
command=/usr/bin/ceph-osd -i 0
autorestart=true